spring:
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: v145sdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQA
  datasource:
    url: jdbc:mysql://squizdb.c7yy48g2y03l.ap-northeast-2.rds.amazonaws.com:3306/squizdb
    username: root
    password: a123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
